### ISSUE TITLE
To Do for 25/03

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#10]
# Bugs des Items :

- [x] <3+<3=<3<3 : Les sprites de double coeur ne se chargent pas.
- [x] 3D Glasses : Recoder tout sur la base de filer 20/20 et de l'enlever. Bien vérifier que ça n'empêche pas le pop de 20/20 seul.
- [x] Bubble's Head + Sun Wukong : Les larmes feuille en général filent une couleur aux ennemis. Les boss ne doivent pas la conserver.
- [x] Cricket's Paw : Le x1,2 s'applique au damage actuel et non à la stat de damage générale.
- [x] Cricket's Tail : Le taux de pop est trop élevé. Essayer de tendre vers 1 chance sur 5.
- [x] Dad's Beer : Confusion à appliquer de manière permanente sur les ennemis normaux. Parfait pour les boss actuellement.
- [x] Dionaeamuscipula : La phase 1 n'absorbe plus les tirs donc impossible de tester plus loin.
- [x] Mizaru : Devrait pouvoir varier seulement quand on tire et moins fréquemment.
- [x] Solomon : Travail sur la collision des coeurs non ramassables.
- [x] Spider Shot : Les larmes spider doivent ralentir au toucher. Bonus x2 damage sur les larmes spider à appliquer.
- [x] Spinach : Baser le damage up sur les damage up de même type (pentagram, growth hormones, synthoil).
- [x] Sun Wukong : Travail ambitieux à effectuer sur la chaîne de familier mais qui aidera pour l'ajout d'autres familiers type RNG Baby.
- [x] Ottid : Corriger la detection des items actifs
- [ ] Kikazaru : Développer la même chose que pour Tech 0. Il est pour l'instant trop facile de ne pas provoquer les larmes qui devraient sortir par les oreilles

# Mécaniques :

- [ ] Cricket Transformation : Les cailloux bloquent souvent le passage avant de casser. Système de pont à coder.
- [ ] Tech Transformation : Le laser jaune ne ralentit pas. Les effets ne rotatent pas.
- [ ] Blessings : Faire pop un bandeau différent annonçant la blessing. Au dessus du bandeau étage à chaque fois.
- [x] Permettre la sauvegarde de tables dans le système de sauvegarde
- [x] Ajouter Mom's Cake dans les items pour la transfo mom
- [ ] Coder la synergie entre box of friends et les familier customs
- [ ] Ajouter le bomb bum à la transfo superbum
- [ ] Tous les Items de boss font leur effet qu'une seule fois. Coder un système pour les prises x2 (avec diplopia par ex)
- [x] Coder prise de ottid x2

**Comment by Shisheyu** [comment]
# Bugs trouvés

- [x] 3D Glasses : Si utilisé pendant que le joueur a Double Shot, le costume de Double Shot disparaît.
- [ ] Dad's Beer : Effet de 6 secondes sur les mobs normaux et non infini comme désiré.
- [ ] Cricket's Paw : Bug avec les Damage Up rajoutés par le mod (Spinach et Pizza)
- [x] Dionaea : Ne bloque toujours aucune larme en phase 1
- [ ] Cataract : Bug qui fait augmenter trop fortement les damage
- [ ] Dionaea : Phase 3 cassée, elle se barre sans la corde
- [ ] Soul Extension : Le sprite des coeurs bleus ne bouge pas. Collision à coder.

**Comment by Dogeek** [comment]
- [ ] lol
