### ISSUE TITLE
Bugs restants à fix pour le 1/04

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#17]
# Bugs des Items

- [x] Kikazaru : Développer la même chose que pour Tech 0. Il est pour l'instant trop facile de ne pas provoquer les larmes qui devraient sortir par les oreilles
- [ ] Zodiac : Gemini - Si le personnage prend un dégât, Gemini se détâche et deal de meilleurs damages
- [ ] Spidershot : toiles d'araignées spawn ne doivent pas ralentir isaac
- [x] Dad's Beer : Effet de 6 secondes sur les mobs normaux et non infini comme désiré.
- [ ] Cricket's Paw : Bug avec les Damage Up rajoutés par le mod (Spinach et Pizza)
- [x] Cataract : Bug qui fait augmenter trop fortement les damage
- [x] Dionaea : Phase 3 cassée, elle se barre sans la corde
- [x] Soul Extension : Le sprite des coeurs bleus ne bouge pas. Collision à coder.

# Mécaniques

- [x] Cricket Transformation : Les cailloux bloquent souvent le passage avant de casser. Système de pont à coder.
- [ ] Tech Transformation : Le laser jaune ne ralentit pas. Les effets ne rotatent pas.
- [ ] Blessings : Faire pop un bandeau différent annonçant la blessing. Au dessus du bandeau étage à chaque fois.
- [x] Coder la synergie entre box of friends et les familier customs
- [ ] Ajouter le bomb bum à la transfo superbum
- [ ] Tous les Items de boss font leur effet qu'une seule fois. Coder un système pour les prises x2 (avec diplopia par ex)

**Comment by Shisheyu** [comment]
- [x] Larmes feuilles : Le joueur peut tirer des larmes feuille quand il a le couteau. Surement pareil avec tous les autres modificateur de larmes type Brimstone, Technology, etc.
- [x] Cricket's Transformation : Les cailloux bloquent encore, les ponts popent une fois sur 1000 ou alors que à une certaine vitesse/certain angle. La transformation ne se déclenche que sur certains items, pas tous.
- [ ] Cricket's Tail : Les coffres popent dans des salles vides sans ennemi. Les coffres popent sur les boss. Les coffres popent encore beaucoup trop ?
- [ ] Soul Extension : Les coeurs ne s'animent que quand le joueur a full vie. Les coeurs ne sont plus doublés si le joueur a full vie. Parfois impossible de ramasser des coeurs rouges quand le joueur est blessé dans les coeurs rouges.

**Comment by Shisheyu** [comment]
- [ ] Sun Wukong : Si le joueur possède Mom's Knife, le familier ne tire qu'à droite. Brimstone nickel.
- [ ] Dionaea : Coder la limite de 3 larmes mangées/comptées par salle. Travailler avec les spriters sur l'anm2 de la corde de boules.
- [ ] Explosive Banana : La banane se lance, elle devrait donc passer au-dessus des trous (langues de vide).
- [ ] Mizaru : Recoder en random -3/+0/+3. Demander à Shisheyu. 
- [x] Spider Shot : Ne fait rien à 0 de luck.
- [x] Bomb Bum : Faire pop un trinket toutes les 5 bombes et non 10. Ajouter le son de ramassage des bombs par le bum, même son que quand Isaac ramasse lui même une bombe.
- [x] Blobby : Ne fait rien à 0 de luck.
