### ISSUE TITLE
Améliorations (facultatives) et bugs mineurs

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#25]
**Non facultatif**

 - [ ] Ajouter le bomb bum à la transfo superbum

 - [ ] Tous les Items de boss font leur effet qu'une seule fois. Coder un système pour les prises x2 (avec diplopia par ex)

**Facultatif**

None

**Bug Mineur**

- [ ] Un peu tout les stats up : faire apparaître un co-op baby permet de ravoir le bonus de stats ( permet même de dépasser les caps du jeu , c'est a dire , plus de 3 de speed , un tear rate négatif , shot speed négatif )
- [ ]  Appetizer, Pepper Spray, Rattle : N'arrivent pas à dépasser la limite de 5 si le joueur a le droit de le faire
- [ ] Cricket's Paw : Spinach + Hot Pizza Slice buggent sur leur premier proc de paw.
- [ ] Mizaru : Problème à la limite de 5 tear rate du jeu

**Comment by Shisheyu** [comment]
Merci de ne pas close.
