### ISSUE TITLE
[Medium Priority] Transfo zodiac : gemini ne se détache pas / taurus donne de l'invincibilité à l'infini

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#29]

**Comment by Shisheyu** [comment]
- [ ] Soul Extension : Many things.

- [x] Transfo Cricket : Transformation directe sur la tête de cricket.

- [ ] Cricket's Paw : Spinach + Hot Pizza Slice buggent sur leur premier proc de paw.

- [x] Dionaea : Une fois le nombre de larmes absorbées par salle atteint, la plante ne bloque même plus les larmes. Le sprite phase 3 ne s'affiche pas.

- [x] Medusa's Head : Recoder de telle façon à ce qu'elle stun bien les ennemis (demi-plan)

- [x] Black Candle : Charger le sprite perso fait par l'équipe à la place de l'existant.

- [x] Zodiac : Rework les effets censés être basés sur la luck.
