### ISSUE TITLE
[] [Bug] Lancer une banane dans un pit fait crasher [Linux]

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#32]

**Comment by sbordeyne** [comment]
j'ai retest, ça fait toujours crasher
si tu peux tester dans une VM...

**Comment by Krayz** [comment]
ça marche sous mon nunux, re ouvre si ça fonctionne tj pas sur ubuntu

**Comment by sbordeyne** [comment]
ça fait toujours crasher mais je pense que c'est un bug d'isaac en lui-même en vrai, je voiis pas d'autre raison

**Comment by Krayz** [comment]
en même temps t'as écrasé mon fix....

**Comment by Krayz** [comment]
y'as plus de 10 commit qui on été revert la, dont le fix(la raison?lel) que j'avais mis en place pour linux, c'est passé quoi?
(le probleme linux est(étais) réglé)
[edit]whatever, j'repush le fix.
