### ISSUE TITLE
Trouvailles d'avant Live

### ISSUE THREAD

**Issue by Shisheyu** [Shisheyu/AfterBrasse#36]
**High Priority**

- [x] Cricket Transformation : Les araignées ne spawnent plus

- [x] Soul Extension : Revoir le tout.

- [x] Solomon : La barrière de coeurs ne fonctionne plus.

- [x] Medusa's Head : Pour l'instant, le stun s'applique en fonction de la direction de tir et non de la position de la tête/déplacement.

- [x] Dionaea : La phase 1 ne bloque plus les larmes une fois les 3-4 absorbées. Phase 2 is ok. Phase 3 is ok.

**Medium Priority**

- [ ] First Blood : Tracker pourquoi la larme disparait à l'affichage des fois

- [x] Blank Tissues : Trouver un meilleur sfx

**Low Priority**

- [x] Chorana : Le changement direct entre une petite salle/grande salle et inversement ne marche pas niveau costumes.

- [x] Black Candle : Charger sprite costume différent, chercher sur le net/modding of isaac si c'est possible.

**Comment by Krayz** [comment]
Pour tout remplacement d'une ressource de base du jeux tel que le skin de Black Candle il suffit de rename l'anm2 custom comme l'anm2 de base(à remplacer). (même principe que pour la modif de l'écran d'accueil)
