### ISSUE TITLE
Needed to release

### ISSUE THREAD

**Issue by Shisheyu** [Shisheyu/AfterBrasse#37]
**High Priority**

- [x] Intégrer transfo bubbles

- [x] Bandals de Blessings : c'est parfait à un détail près, la synchronisation des anm lors d'un appui sur tab. Il faut pour l'instant rester appuyé au moins 59 frames pour que les anm partent en même temps.

- [x] Soul Extension : multiples détails. Voir avec shi pour la liste.

- [x] Load les bandeaux de transformation (attention à Ottid ?)

- [x] Load les bandeaux de Blessings en début d'étage automatiquement (is ok pour l'appui select, sauf au début d'un étage où le code fait n'imp pour l'instant)

- [x] Transformation Cricket : Ne fait pas pop d'araignées

- [x] Blank Tissues : Devient un spacebar qui se recharge auto en 10 secondes après utilisation

- [x] Soul Extension : Load les anm2 de battement de coeurs

- [x] Ottid : Bug avec les transformations du jeu de base

**Medium Priority**

- [ ] Mizaru : Problème à la limite de 5 tear rate du jeu

- [x] Blobby : Travailler avec un spriter (c'est sinkineit qui a fait le costume) pour que le blobby n'ouvre sa bouche que quand il tire

- [x] Blobby : Intégrer le sprite corrigé de Blobby (afin qu'il bouge quand la tête d'isaac descend lors d'un tir)

**Low Priority**

- [ ] Appetizer, Pepper Spray, Rattle : N'arrivent pas à dépasser la limite de 5 si le joueur a le droit de le faire

- [ ] Cricket's Paw : Spinach + Hot Pizza Slice buggent sur leur premier proc de paw.

**Comment by Shisheyu** [comment]
Merci de ne pas close prématurément, même si toutes les cases sont pensées "à cocher".

**Comment by sbordeyne** [comment]
j'ai copié collé les issues qui ne seront pas fix pour la release (mizaru et les low prio) dans l'issue un peu "bowdel pas très important"
