### ISSUE TITLE
Zodiac (needed to release)

### ISSUE THREAD

**Issue by Shisheyu** [Shisheyu/AfterBrasse#38]
- [x] Scorpio : RAS

- [x] Pisces : RAS

- [x] Libra : RAS

- [x] Cancer : RAS

- [x] Leo : RAS

- [x] Aquarius : RAS

- [x] Saggitarius : enlever le shot speed down sinon RAS

- [x] Virgo : ne donne pas l'effet de la pilule comme le PHD, ne fait apparemment rien pour l'instant

- [x] Capricorn : CHANGEMENT, ajouter le all stats up une nouvelle fois. Virer l'ancien code

- [x] Aries : CHANGEMENT, chance de negate un damage à la manière de Cone Head. Virer l'ancien code

- [x] Taurus : CHANGEMENT, gros speed up genre +0,8 ce qui permettra au joueur d'aller plus rapidement à l'état invincible. Virer l'ancien code

- [x] Gemini : CHANGEMENT, on enlève la condition de se faire toucher. Le code devient, une fois transformé en Zodiac, Isaac n'a pas plus de Gemini attaché à lui mais le familier volant Gemini vénère qui chasse les ennemis au contact et deal deux fois le damage du Gemini de base attaché.

**Comment by sbordeyne** [comment]
virgo c'est pas possible pour le moment, AddCollectibleEffect a quelques bugs, et l'effet du PhD d'affichage des pills ne marche pas

**Comment by Shisheyu** [comment]
Aucun problème, pour l'instant on rajoute PHD au joueur comme on fait avec 3D Glasses.
On le note quelque part pour effectuer le changement lorsque AddCollectibleEffect marchera.

**Comment by sbordeyne** [comment]
ok done

**Comment by sbordeyne** [comment]
tout est fait, je close du coup
