### ISSUE TITLE
Larmes feuilles de bubbles bugguées 

### ISSUE THREAD

**Issue by sbordeyne** [Shisheyu/AfterBrasse#42]
J'ai grosso modo copié collé ton code de bubbles head pour faire les larmes feuilles de la transfo bubbles mais elles sont assez... Chelou, je te laisse tester, surtout avec kikazaru (les larmes a 90 degré)

Tu peux y jeter un oeil ?

**Comment by sbordeyne** [comment]
j'ai tenté un changevariant (classe entity tear) sans succès

**Comment by Krayz** [comment]
j'ai déjà fait une update pour ça il y as un peut plus de 4 heures. du coup j'vais close pour bien que tu vois cette fois :p
