### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Shisheyu** [Shisheyu/AfterBrasse#44]
- [x] Bubbles Jump : Les cailloux, pots, cacas cassés restent jumpables.

- [x] Bubbles Leaf Tears : Toujours des problèmes, toutes les larmes ne sont pas leaf.

- [x] Capricorn Zodiac : Ne donne pas les stats comme voulu

- [x] Blobby : Il faut tirer au moins 2 larmes pour que ça marche, strange.

- [x] Bandals Transfos : Laisse une mini trace de chiasse sur leur dernière frame.

- [x] Sprites à Upload : Corps de Bubbles modifié et Spritesheet de Zodiac modifié.

- [ ] Post-its.

**Comment by sbordeyne** [comment]
@Krayz : je pense que le problème des leaf vient de la fonction GetClosestTear en fait. Il faudrait peut-être remplacer toute tear tirée par le joueur par des larmes feuilles ?

**Comment by Krayz** [comment]
@Dogeek  à la base le vrai probleme c'est que tu as _copier/coller_ du code qui n'as pas été écris pour ce que tu as l'air de vouloir faire ^^'
[edit]Normalement ça marche comme tu veux maintenant
